#!/bin/sh

### BEGIN INIT INFO
# Provides:          helloworld
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Hello to the world   
# From : https://gist.github.com/Alexniver/93168c5b503836f540cc
### END INIT INFO

case "$1" in
start)
        start-stop-daemon --start --background --exec /home/tom/dev/helloworld
;;
stop)
        start-stop-daemon --stop --name helloworld
esac
