#!/bin/sh

### BEGIN INIT INFO
# Provides:          helloworld
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Hello to the world   
# From : https://gist.github.com/Alexniver/93168c5b503836f540cc
### END INIT INFO

case "$1" in
start)
        # 
        #   start-stop-daemon --start --background --exec /home/tom/dev/helloworld
        # 上面的语句似乎对二进制文件并不有效,下面的是复制了mysql 的启动脚本的语句
        su - root -s /bin/sh -c "/root/helloworld/ > /dev/null 2>&1 &"
;;
stop)
        start-stop-daemon --stop --name helloworld
esac


#开机启动
# update-rc.d helloworld defaults 99

#运行服务前记得修改服务脚本权限
# chmod 755 /etc/init.d/chinacoind
